### ISSUE TITLE
Support for window resizing

### ISSUE THREAD

**Issue by AberDerBart** [davidferguson/pibakery#1]
It would be nice to be able to resize the PiBakery window to have more space for editing (tested on Windows).

**Comment by davidferguson** [comment]
Blockly makes window resizing a little trickier than I'd like, but I've just had a play, and it should be possible. I'll try and add it to the next update - follow [@PiBakery on twitter](http://twitter.com/PiBakery) to get news of when I release that.

**Comment by AberDerBart** [comment]
Nice, thank you very much. PiBakery is a great tool, I have been
searching for something like this for a long time.

**Comment by Earl-Brown** [comment]
I just created a pull request that will at least allow the window to resize.

When resizing, the scroll bars "jump" a bit, and sometimes don't align to the window edge correctly.

Also, it would be nice to save/restore window metrics (position, size)

**Comment by davidferguson** [comment]
PiBakery source now supports Window resizing; currently it doesn't save window metrics but I'll look into adding that in the future.
