### ISSUE TITLE
Linux: 'npm install'  fails on Ubuntu Zeisty for macmount 

### ISSUE THREAD

**Issue by kradan** [davidferguson/pibakery#102]
Can't install PiBakery with [this method](https://diyautomate.me/2016/11/26/base-installation-of-raspbian-jessie-lite-for-use-in-home-automation-architectures/):
```
npm WARN optional Skipping failed optional dependency /denymount/macmount:
npm WARN notsup Not compatible with your operating system or architecture: macmount@1.0.0
npm WARN optional Skipping failed optional dependency /resin-image-write/diskpart:
npm WARN notsup Not compatible with your operating system or architecture: diskpart@1.0.2
```

**Comment by davidferguson** [comment]
Those aren't errors, they're just warnings meaning that the install will still continue past them. PiBakery should still work!
