### ISSUE TITLE
When is Linux support going to be ready?

### ISSUE THREAD

**Issue by mikelpint** [davidferguson/pibakery#119]

**Comment by PeterChauYEG** [comment]
Hi,

I was able to install PiBakery by following the install from [source instructions](https://github.com/davidferguson/pibakery/). I had issues with node and was able to fix that by using `nvm` to install `node 9.0.3`. Don't forget setup your os'.

**Comment by mikelpint** [comment]
OK, thank you.

**Comment by pintman** [comment]
This seems to be duplicate of #110.

**Comment by davidferguson** [comment]
Closing as duplicate of #110
