### ISSUE TITLE
Any way to show the long bash script progress on startup?

### ISSUE THREAD

**Issue by zkidez** [davidferguson/pibakery#122]
i added a bash script to the "on every Boot", but i think its not executed. 
Is there any chance to see the bash progress in Terminal! after startup?

or to open the bash in the terminal window. I Just want that its be shown.

**Comment by davidferguson** [comment]
Currently there's no way to see the progress during startup, however PiBakery does create a log file located `/boot/PiBakery/everyBoot.log` which shows the output log of all blocks that have run under **On Every Boot**. If your script prints anything, it'll end up in there.
