### ISSUE TITLE
Pretty print exported XML

### ISSUE THREAD

**Issue by kalliste** [davidferguson/pibakery#125]
I'm deploying Pi systems for an IoT application and so I have my recipe in a git repository. It helps to have the xml data split across multiple lines so I can look at the diff and see what changed between versions. The current version packs everything on one line.

It seems like pretty print should be the default behavior for the export function.

**Comment by kalliste** [comment]
Pull request is #126

**Comment by davidferguson** [comment]
This has been implemented in PiBakery v2.
