### ISSUE TITLE
Cannot load previous setup

### ISSUE THREAD

**Issue by nickm324** [davidferguson/pibakery#131]
When running PiBakery with an SD card in the reader that contains a previous setup PiBakery sees its there and asks if I want to load that setup and when I click yes nothing happens and nothing is loaded. After it says it loaded the previous setup no blocks are displayed and the blocks that should be displayed are no longer available from the tools boxes on the left.
![pibakeryrun](https://user-images.githubusercontent.com/6774571/37171413-735d60c6-22d3-11e8-8a6b-955b9707749a.PNG)

**Comment by davidferguson** [comment]
When you choose to load in your old setup, it won't load in the "On First Boot" blocks, if you've already booted your Pi, because they've been executed and can't be changed any more.

Additionally, the "On First Boot" block will be converted to "On Next Boot".
