### ISSUE TITLE
Make blocks submission via PRs to this repo.

### ISSUE THREAD

**Issue by mariotti** [davidferguson/pibakery#138]
It is a bit of an issue for me if I have to submit a code block to a different repo.

1) I will not see it in my code
2) I have to make copy/paste and sync different repos

Why submitting blocks cannot be done in this repo as a normal PR?

**Comment by davidferguson** [comment]
Apologies for the delay in replying.

They're in a seperate repo because that makes it much easier to update them separately from the app. And in PiBakery v2, multiple block repos can be set in PiBakery.
