### ISSUE TITLE
keep track of status

### ISSUE THREAD

**Issue by mariotti** [davidferguson/pibakery#140]
If I apply for example the wifisetup on the same SD, on the nextBoot tab, I get the

/etc/wpa_supplicant/wpa_supplicant.conf 

flooded with the same wifi configuration.

It would be nice if we can track a form of status. Like:
 - block already applied on nextBoot with ID: xnfhdhs32dj

For this special case we could parse the config for the SSID and replace it,
but I am not sure this might be a general solution.

Maybe a more general solution is to keep track of the status of applied blocks
and "versioning" the status of an SD.

In particular for the nextBoot things.

Sorry for the spam. I think it is a very nice tool but needs improvements.
None the less I started to use it for some practical project.

Thanks for the work already done!

**Comment by davidferguson** [comment]
Apologies for the delay in replying to this.

As a block just executes a script (can be anything, bash, python, etc), it's impossible to implement a mechanism in PiBakery itself to track the status of what has been changed.

A better alternative would be to improve the WiFi block to stop it adding duplicate entries to wpa_supplicant.conf. If this would be of interest, open an issue (or pull request!) in [davidferguson/pibakery-blocks](https://github.com/davidferguson/pibakery-blocks).
