### ISSUE TITLE
Create PiBakery.pkg for macOS?

### ISSUE THREAD

**Issue by jedahan** [davidferguson/pibakery#145]
Can we get a v0.3.8 PiBakery.pkg so homebrew cask can use the latest binaries?

**Comment by davidferguson** [comment]
There actually is one, it's just rather unfortunately a little too large to fit on GitHub releases. Therefore I'm hosting it on my own servers, you can grab a copy from [the PiBakery.org Mac download page](http://pibakery.org/docs/install-mac.html).

**Comment by jedahan** [comment]
Is there a way to rename it to include the version number? If so I could then submit a pull request to homebrew-cask.
Thanks!
