### ISSUE TITLE
Feature Request: Pretty print JSON images.json

### ISSUE THREAD

**Issue by gauntface** [davidferguson/pibakery#146]
When PiBakery runs, it reads and writes data to and from images.json.

Would you be open to taking a PR to format the json a little instead of a single line?

Just simple change to `JSON.stringify(data, null, 2)` instead of `JSON.stringify(data)`.

**Comment by davidferguson** [comment]
PiBakery is actually in the process of being completly re-written (which is why I've been slow to accept PR and answer issues), with release due to be in the next few days/this week. This update will have this feature.

I'll leave this open until the new version is available.

**Comment by davidferguson** [comment]
> I'll leave this open until the new version is available.

Now released.
