### ISSUE TITLE
Feature Request Change config without reflashing

### ISSUE THREAD

**Issue by DragonHunter274** [davidferguson/pibakery#148]
I don't know if this is possible but can you add  the ability to change for example the wifi credentials without reflashing the sd card? 

EDIT: I see it is possible with sd cards flashed with pi bakery before.
Is it possible to do that with an sd card that has been flashed by a different tool? 

EDIT 2: I just tried to use the update button in the ui but it doesn't react to being clicked on 

EDIT 3: apparantly ther is a bug if you have multiple storage devices connected it tries to write to the wrong one in the console it then says blocks.xml not found (which it can't find it is searching on the wrong drive)

**Comment by davidferguson** [comment]
In response to initial question: Currently it's possible for SD cards that were written with PiBakery. However in the next few days a major update will be released that will support editing SD cards that weren't written in PiBakery.

----

>EDIT 2: I just tried to use the update button in the ui but it doesn't react to being clicked on

>EDIT 3: apparantly ther is a bug if you have multiple storage devices connected it tries to write to the wrong one in the console it then says blocks.xml not found (which it can't find it is searching on the wrong drive)

Hmm, interesting. I probably won't fix this for now, as the new update mentioned above edits SD cards in a different way, and therefore this should no longer be an issue.

I'll leave this open until the new version is available.

**Comment by davidferguson** [comment]
> However in the next few days a major update will be released that will support editing SD cards that weren't written in PiBakery.

Now been released (although still a pre-release - **there will be bugs!**)
