### ISSUE TITLE
JavaScript error when I try to write to SD card

### ISSUE THREAD

**Issue by ReubenBTalbott** [davidferguson/pibakery#157]
I am using the 2.0 Pre-Release and I get this error when I try to write the image to the SD card.
![error pi bakery](https://user-images.githubusercontent.com/19376692/43080085-e269b6fa-8e5c-11e8-9515-6f3a507f9d70.PNG)

**Comment by davidferguson** [comment]
Interesting, quite a few people have reported this error. I presume you're running Windows 10? I'll have a look into it.

**Comment by davidferguson** [comment]
Should be fixed now, I'll be releasing a build with the fix soon, but am aiming to fix a few other issues first.
