### ISSUE TITLE
How to run apt-get commands 

### ISSUE THREAD

**Issue by exocode** [davidferguson/pibakery#159]
How do I run commands like 
- `sudo python setup.py install`

I know simple commands work like this:

<img width="438" alt="bildschirmfoto 2018-07-25 um 21 38 44" src="https://user-images.githubusercontent.com/1597621/43223381-304ead60-9053-11e8-9c6e-dfab22f5f49c.png">

But how to run commands like install from my example above?

**Comment by davidferguson** [comment]
Under `Other`, there is a `Run Command` block, which should be suitable for you.
