### ISSUE TITLE
Copy / Paste in Blocks (2.x)

### ISSUE THREAD

**Issue by exocode** [davidferguson/pibakery#160]
In version 1.x I was able to copy/paste content from outside PiBakery into a field (for example Network and Network Password). This is in version 2 not possible anymore. I am only able write everything by hand, which is a bit annoying, because I use long Wifi passwords...

 ![bildschirmfoto 2018-07-28 um 14 47 33](https://user-images.githubusercontent.com/1597621/43356674-43ed2ee0-9275-11e8-816a-cf7e9e8bd02f.png)

**Comment by exocode** [comment]
For now: I found out that drag-and-drop from another app is (still) working. I use a mac.

- select the field you wanna drag in PiBakery
- select your text in a Texteditor
- drag and drop the text into the field

**Comment by davidferguson** [comment]
That's odd, it should work in PiBakery v2. v2 uses a different (better) copy-paste system. Do you have options to copy-paste from the Edit menubar?

**Comment by exocode** [comment]
The menu bar does not even exist on Mac. Only when I recompile the whole app with `electron .`.
It also is not present when I compile with `electron-packager .`

**Comment by davidferguson** [comment]
A very silly bug - I forgot to run the createMenu() command which creates the menu (and enables copy-pasting).
