### ISSUE TITLE
Cant find sd

### ISSUE THREAD

**Issue by rhthaakkar** [davidferguson/pibakery#162]
I have tried with bith win10 and win8.. It goes till end and then shows error "can't find sd" 
Pibakery 0.3.8 and Nitro 8GB sd card
![img_20180808_224253_1](https://user-images.githubusercontent.com/42216974/43879223-8b091952-9bc0-11e8-8994-2ab1c228e417.jpg)

**Comment by davidferguson** [comment]
This error indicates that the SD card didn't automatically re-mount once writing was finished.

If you write it again:
1) do you get the same error?
2) if you go to `Windows Explorer -> Computer`, is the SD card listed there? (probably as `boot`)

**Comment by rhthaakkar** [comment]
Yeah.. I tried to write again and card was also showing in explorer after
remount but pibakery couldn't detect it.. Changed the card and then
worked..

**Comment by davidferguson** [comment]
Odd. SD cards can be weird sometimes.
