### ISSUE TITLE
Fedora aarch64

### ISSUE THREAD

**Issue by Blindripper** [davidferguson/pibakery#167]
Is a support of that Distro planned?
What is to do, to support other distros?

BTW Cool project !

**Comment by Blindripper** [comment]
Forgot to mention that a Tezos Core Dev recommend this distro.

https://gitlab.com/tezos/tezos/issues/271#note_91200988

**Comment by davidferguson** [comment]
Supporting other distros is tricky, as it requires that all the block scripts be written to be compatible with both Debian based distros (as they are currently) and also other distros.

For the moment I'm not officially supporting this, but if people were willing to go and rewrite the [PiBakery block scripts](https://github.com/davidferguson/pibakery-blocks) to be compatible with other distros and submit pull requests, I'd be more than willing to accept them.
