### ISSUE TITLE
PiBakery.org TLS certs are wrong

### ISSUE THREAD

**Issue by na-g** [davidferguson/pibakery#168]
I am not sure where else to report this. The PiBakery.org TLS certs are for the wrong domain.

    pibakery.org uses an invalid security certificate. The certificate is only valid for dragonisland.hictooth.com.

**Comment by davidferguson** [comment]
Ah, thanks for pointing this out. I seemed to have misconfigured it with certbot - but it's fixed now.

**Comment by mortenmoulder** [comment]
It's broken again since mid December.
