### ISSUE TITLE
Cannot download Raspbian image

### ISSUE THREAD

**Issue by peterschussheim** [davidferguson/pibakery#18]
Hi,

I am trying to use pibakery from source (0.2.3) using the instructions given in the project docs and after clicking through so the raspbian image downloads, the application just sits indefinately.  Below is a screen of the console errors.

My machine is running OSX 10.11.16.
---
![2016-09-08_18-47-29](https://cloud.githubusercontent.com/assets/3654683/18369680/425679d6-75f5-11e6-895e-3f0ab319ca09.jpg)
---

thanks,
peter

**Comment by davidferguson** [comment]
Ah - I need to update my docs for installing from source!

PiBakery now looks for the image in `/Library/Application Support/PiBakery`, which won't exist if you downloaded the source and not the installer. You'll need to navigate to `/Library/Application Support/` in Finder and then create a folder called `PiBakery` manually. After which, the image should download and extract into that.

Apologies for this - and hope this helps!
