### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by davidsharp** [davidferguson/pibakery#28]
I noticed this project was missing a license, as I was curious if/how I could use this as part of a larger project and I don't know where I would stand with such a thing.

**Comment by davidsharp** [comment]
Actually, I've just noticed the license in the `main.js`.

A LICENSE.md would still be nice.

**Comment by davidferguson** [comment]
I've got it as [COPYING](https://github.com/davidferguson/pibakery/blob/master/COPYING), which I've seen in a few other projects.

I've just looked at https://www.gnu.org/licenses/gpl-howto and it recommends using COPYING, so unless there's an issue with using that, that's what I'll stick with.

**Comment by carlosperate** [comment]
Looks like github only picks up the License to display on the front page if using the `LICENSE` filename. 
https://help.github.com/articles/adding-a-license-to-a-repository/

Not a good enough reason to rename your file, but I though it'd be interesting to share. I woudn't be surprise if a future update also supports `COPYING`.
