### ISSUE TITLE
No feedback when loading bad block

### ISSUE THREAD

**Issue by dsbert** [davidferguson/pibakery#35]
I was attempting to create a new block on OS X. When dropping my folder, I received no feedback and the block was not added. It took me a while to figure out that it was failing because I had an error in the json configuration file. It would be very helpful if pibakery could report errors when attempting to load a new block.

**Comment by davidferguson** [comment]
This should be easy enough to add in - I'll add it into the next PiBakery update!

**Comment by davidferguson** [comment]
It's now in PiBakery if you build from source, and I plan on releasing updated installers over the weekend.

**Comment by dsbert** [comment]
Awesome. Appreciate the quick response.
