### ISSUE TITLE
PiBakery can't be installed on this disk OSX

### ISSUE THREAD

**Issue by WilkinsPhysics** [davidferguson/pibakery#59]
See screenshot. I downloaded the .pkg file from http://www.pibakery.org/docs/install-mac.html

<img width="616" alt="screen shot 2016-09-27 at 19 19 15" src="https://cloud.githubusercontent.com/assets/3629138/18886325/5bbb5ce2-84e7-11e6-8f95-34216fc6e3fb.png">

For reference, I'm on a MBP 13 inch, early 2015 - El Capitan Version 10.11.6. The only thing I can think of is that the actual install is >6Gb? but I doubt it.

I see this issue was reported as fixed ~6 days ago, seems it has resurfaced, or I have the old pkg (I don't think this is the case)

EDIT: Seems I was incorrect, and ~7Gb is required before the application will let you pass the 'Destination Select' section of the installer, even if you don't plan on installing Raspbian full.

**Comment by davidferguson** [comment]
The pig should be able to use what options you've selected to calculate the space required - although I think I may have this configured incorrectly. I'll have a look and see if I can fix this.
