### ISSUE TITLE
Support for community blocks: add a folder for blocks under documents

### ISSUE THREAD

**Issue by berryelectronics** [davidferguson/pibakery#61]
I dont think that each and every block has to be in it by default, so to have something like a forum where a user can download custom blocks (which may or may not be relative specific for a special use) and add them in a folder in his documents (like user libraries in the arduino IDE, a button to add the zip)

**Comment by davidferguson** [comment]
PiBakery v2 now supports multiple block sources - this isn't exactly what is described above, however it allows users to add their own block repos into PiBakery.

It's not visible in the UI yet, but this will be exposed in a future release. Progress will be tracked in #56
