### ISSUE TITLE
Using 'apt-get remove' in the run command does not seem to work

### ISSUE THREAD

**Issue by juggledad** [davidferguson/pibakery#7]
If you add a 'Run Command' block and put in an 'apt-get remove xxxxxxx -y' (I was trying to remove node red) it seems to choke on it. If you are booting into console, you will see the boot taking place and at the end of the boot the screen will flash and then you will end up at the login prompt with the cursor flashing. Pressing ctrl-c gets you out so you can login.

Editing the script to log the output to a file I see:
`/boot/PiBaker/blocks/runcommand/runCommand.sh line 3: exec: apt-get remove nodered -y: not found`

**Comment by davidferguson** [comment]
I'v found the bug that was causing this and have fixed it, but I haven't pushed a block update just yet, as there are a few more blocks I want to add into the update. Within a few days, I'll push the update and you'll be prompted to download the new blocks.

Thanks for reporting!
