### ISSUE TITLE
Feature request: block for interactive user input

### ISSUE THREAD

**Issue by LowPowerLab** [davidferguson/pibakery#80]
Would be great to have a block or a way to allow asking the user for input interactively, using whiptail for instance, into a variable that could be used in a later step.
I tried doing this with **RunCommand** to invoke a slave whiptail dialog but the original PiBakery whiptail dialog stays on top (the slave one seems to be in the background and actually accepting input but not visible so its pointless):

`HTTPUSER=$(whiptail --inputbox "Enter the http_auth username" 8 78 "username" --title "HTTP Auth setup" --nocancel 3>&1 1>&2 2>&3)`

**Comment by davidferguson** [comment]
Apologies for the very long delay.

This won't be implemented. PiBakery is primarily used for headless setups, and therefore a block requiring user input would be an outlier.
