### ISSUE TITLE
Download timed out

### ISSUE THREAD

**Issue by yehan2002** [davidferguson/pibakery#84]
the download times out in 30 minutes every time I try to download pibakery
![screenshot at 2016-12-15 18-14-32](https://cloud.githubusercontent.com/assets/19862951/21224501/88d71d9e-c2f2-11e6-8659-370a58b56853.png)

**Comment by joshghent** [comment]
@yehan2002 https://github.com/davidferguson/pibakery/issues/99 is possibly being worked on to allow to download as a torrent.

@davidferguson Possibly worth closing this since it's quite old?
