### ISSUE TITLE
Add an option to export, to export the /boot/PiBakery folder

### ISSUE THREAD

**Issue by youngsoul** [davidferguson/pibakery#85]
I would like to export the contents of the /boot/PiBakery folder, without having to burn a SD card.  

Would it be possible to add an option, or to always include the /boot/PiBakery folder as part of the export?

Thank you

**Comment by davidferguson** [comment]
Apologies for the very long delay!

It would be possible, but I can't think of much of an use for it? Especially now with PiBakery v2, which allows you to insert any Raspbian SD card and apply PiBakery to that without re-writing the image.
