### ISSUE TITLE
Cron job support

### ISSUE THREAD

**Issue by adrienemery** [davidferguson/pibakery#9]
The ability to support cron job configuration would be really useful. Is there any plan for this (or maybe I missed it).

Thanks for the great work on this!

**Comment by davidferguson** [comment]
It's not one that I'd though of, but I can certainly add it in! I can't garentee when though, as I have a few block suggestions and bug fixes to get through first.

However, if you want to create and submit a block for it, then have a look at the [Contributing Guide](http://www.pibakery.org/docs/contribute.html) on the PiBakery website.

**Comment by davidferguson** [comment]
This has now been committed into the [pibakery-blocks repo](https://github.com/davidferguson/pibakery-blocks). I plan on pushing out a block update this weekend, which will include this block.

**Comment by adrienemery** [comment]
thank you. PiBakery is awesome!
