### ISSUE TITLE
Feature request: Cancel button when writing to SD

### ISSUE THREAD

**Issue by mn1del** [davidferguson/pibakery#93]
Firstly, I love PiBakery, so thank you! I have a feature request - fairly self-explanatory from the subject field. The issue is when I hit "write", and then immediately realise that there's something I'd like to change... I need to wait for it to finish Writing to SD with apparently no way of cancelling it.

Keep up the great work!

**Comment by davidferguson** [comment]
Currently PiBakery uses [etcher-image-write](https://github.com/resin-io-modules/etcher-image-write) and [CommandLineDiskImager](https://github.com/davidferguson/CommandLineDiskImager) to write the image (although will move to just using **etcher-image-write** in the future). Sadly both of these don't offer a cancel/abort/pause feature yet, so it's not something I can easily implement in PiBakery.

The folks who make **etcher-image-write** have been pretty open to suggestions though, so I'll ask them and if it gets implemented, I'll add it to PiBakery too.
