### ISSUE TITLE
vnc server block

### ISSUE THREAD

**Issue by nunziofiore** [davidferguson/pibakery#95]
Hi 
 I read on pibakery web site that there is a block INSTALL VNC SERVER and a RUN VNC SERVER AT PORT xxxx
But I have only that...
<img width="483" alt="screenshot 2017-02-17 18 34 55" src="https://cloud.githubusercontent.com/assets/46832/23076271/0000f230-f540-11e6-869b-ad225b8a2575.png">
how can I have also the other?

**Comment by nunziofiore** [comment]
to manage that problem I wrote that :

![schermata 2017-02-20 alle 09 56 51](https://cloud.githubusercontent.com/assets/46832/23118038/ee78c208-f752-11e6-843a-33741cbe85fd.png)

if you run from a terminal the command I listed in pibakery, you can set the password for vnc by script and in next boot run vncserver, in this way the end user can use vnc client without write ssh or something he doesn't know.

BUT: when I make this instruction in pibakery the password is not setted.
It's possible there' s a bug when you use a ">" that pibakery change in &gt; for xml purpose? How I can avoid this error?

**Comment by Barry4679** [comment]
Hi

<<< I read on pibakery web site that there is a block INSTALL VNC SERVER and a RUN VNC SERVER AT PORT >>>

I think that the web site may be out of date. The latest version of Raspbian included a pre-install version of RealVNC
https://www.raspberrypi.org/blog/introducing-pixel/

I think that was a change to Pi Bakery following that. It is touched one here
https://github.com/davidferguson/pibakery/issues/65

When trying to work through related issues I found the following thread useful
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=161341

**Comment by nunziofiore** [comment]
Thankyou for your answer @Barry4679 . Do you know why the command

`echo password | vncpasswd -f > $HOME/.vnx/passwd`

if launched from command line it runs but if I put it as in the picture in a RUN COMMAND block of Pibakery, it seems that is not launched from pibakery? 
It seems that run command is bugged in some way.

**Comment by nunziofiore** [comment]
I tried several RUN COMMAND but no one seems to work. I tried also a simple "touch file" but nothing. I think that the commandrun block is bugged

**Comment by Barry4679** [comment]
I am not experienced with Linux Nunzio, and I don't have a Raspberry Pi
here at the moment.

Look for the PiBakery folder inside the Rpi. There is a run log file there.
It may hep you.

**Comment by Barry4679** [comment]
I made heavy use of the Run command. I had no issues with it.
Maybe you are having authority issues? Try changing User to Root.

**Comment by nunziofiore** [comment]
tried both as pi and root but nothing... now I'll retry and I'll read the log that I didn't know that there was one. I'll write something tp you in few hours

**Comment by nunziofiore** [comment]
Ok I've got the right recipe to avoid the problem. Thank you 
![schermata 2017-02-20 alle 14 30 10](https://cloud.githubusercontent.com/assets/46832/23127725/591cfb6e-f77c-11e6-8c0a-ae8ae595073c.png)
