### ISSUE TITLE
OS Update Failed on macos sierra

### ISSUE THREAD

**Issue by miguelchico** [davidferguson/pibakery#98]
Hi.

I'm getting this error every time I open PiBakery:
At the beginning a message appears saying a new Raspbian lite is available.
<img width="653" alt="screen shot 2017-05-02 at 23 11 39" src="https://cloud.githubusercontent.com/assets/6106661/25639638/e63e86be-2f8c-11e7-8df9-c5797519ab8a.png">

After I try to update an error message appears:
<img width="649" alt="screen shot 2017-05-02 at 23 11 53" src="https://cloud.githubusercontent.com/assets/6106661/25639675/023253a0-2f8d-11e7-92e5-b64f58725c60.png">

I'm running a fresh install of PiBakery, version 0.3.2

**Comment by benjamin-hering** [comment]
I got a similar error in macOS Sierra (10.12.4). Tried reinstalling PiBakery 0.3.2 with no success. 

Eventually I tried downloading the latest update manually. I discovered where the Base OS files were stored on my local machine `/Library/Application Support/PiBakery/os` and downloaded the [latest pibakery specific raspbian lite version](https://github.com/davidferguson/pibakery-raspbian/releases) from there and extracted it into the OS directory and named it the same as the last Raspian-lite image. Still got the error, though, even though with keeping the same naming convention.

**Comment by davidferguson** [comment]
PiBakery should will display the update prompt when the version number in the file `/Library/Application Support/PiBakery/os/images.json` is less than the version number in `https://github.com/davidferguson/pibakery-raspbian/blob/master/images.json`

The actual error is where it's failing to download the image. If you use the shortcut CMD-Shift-I PiBakery will open the `Developer Inspector`, where if you go to the `Console` tab, you'll see more detailed error details. If this error is still occurring, could you post the detailed errors from that window here?

**Comment by miguelchico** [comment]
Hi!
This is not happening anymore.
Thank you!
